name = "steamcanvas-backend"
compatibility_date = "2024-02-08"
main = "src/index.ts"

# D1 Database Binding
[[d1_databases]]
binding = "STEAMCANVAS_DB"
database_name = "STEAMCANVAS_DB"
database_id = "e5767ee9-4437-412d-938e-cfd230ceafe0"

# R2 Bucket Binding
[[r2_buckets]]
binding = "STEAMCANVAS_ASSETS"
bucket_name = "steamcanvas-assets"
preview_bucket_name = "steamcanvas-assets"

[observability]
enabled = true

[vars]
STEAM_API_KEY = "YOUR_STEAM_API_KEY"
JWT_SECRET = "YOUR_JWT_SECRET"
FRONTEND_URL = "https://steamcanvas.pages.dev" # Production URL
R2_ACCESS_KEY_ID = "YOUR_R2_ACCESS_KEY_ID"
R2_SECRET_ACCESS_KEY = "YOUR_R2_SECRET_ACCESS_KEY"
R2_BUCKET_NAME = "steamcanvas-assets"
R2_ACCOUNT_ID = "74026d70132b64d9df97869631855052"
STRIPE_SECRET_KEY = "YOUR_STRIPE_SECRET_KEY"
STRIPE_WEBHOOK_SECRET = "YOUR_STRIPE_WEBHOOK_SECRET"
