name = "steamcanvas-backend"
compatibility_date = "2024-02-08"
main = "src/index.ts"

# D1 Database Binding
[[d1_databases]]
binding = "STEAMCANVAS_DB"
database_name = "STEAMCANVAS_DB"
database_id = "e5767ee9-4437-412d-938e-cfd230ceafe0"

# R2 Bucket Binding
[[r2_buckets]]
binding = "STEAMCANVAS_ASSETS"
bucket_name = "steamcanvas-assets"
preview_bucket_name = "steamcanvas-assets"

[observability]
enabled = true

[vars]
STEAM_API_KEY = "98FA30A44591DCD6073403FFC7CB68E4"
JWT_SECRET = "SteamCanvas_Super_Secret_2026_!"
FRONTEND_URL = "https://steamcanvas.pages.dev" # Production URL
R2_ACCESS_KEY_ID = "20e4ce8be86b5e3900ff34ebd5148aa1"
R2_SECRET_ACCESS_KEY = "3ed37e7b33ea4bd6e3cd5a1a74d18dce5a234066e7cce4206113f08e5122b014"
R2_BUCKET_NAME = "steamcanvas-assets"
R2_ACCOUNT_ID = "74026d70132b64d9df97869631855052"
STRIPE_SECRET_KEY = "sk_test_PLACEHOLDER"
STRIPE_WEBHOOK_SECRET = "whsec_6a47569ecc19bac872bd82259d5468433a8c1c06d0b0758e304d14bb4734f0f7"
